[package]
name = "highlightjs-rs"
version = "0.1.0"
authors = ["Carsten Kragelund <carsten@kragelund.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuzzy-matcher = "0.3.7"
lazy_static = "1.4.0"
